### Numpy

1. Deeper into NumPy & Pandas

### a) Numpy - Basics

 - Numeric Processing
 
 - Multi Dimensional Array object
 
 - Matrix operation such as Linear Algebra
 
 - Allows faster indexing , slicing operations
 
 - Deep Learning application

In [1]:
import numpy as np

##### if you dont have numpy installed , use pip install numpy

In [2]:
import random
myrandomlist  = [random.randrange(0,10) for x in range(4)]
myrandomlist

[9, 0, 8, 9]

In [3]:
type(myrandomlist)

list

In [4]:
nparray1 = np.array(myrandomlist)

In [5]:
nparray1 = np.array([1,2,3,4])

In [6]:
type(nparray1)

numpy.ndarray

In [7]:
nparray1

array([1, 2, 3, 4])

#### Let's examine the key properties of a numpy object



In [8]:
nparray1.shape

(4,)

In [9]:
nparray1.size

4

In [10]:
nparray1.ndim

1

In [11]:
nparray1.dtype

dtype('int64')

##### Multi dimensional Arrays

In [12]:
mdarray = np.array([[1,4,4],[4,6,2],[8,8,5],[5,3,8]])

In [13]:
mdarray

array([[1, 4, 4],
       [4, 6, 2],
       [8, 8, 5],
       [5, 3, 8]])

In [14]:
mdarray.size

12

In [15]:
mdarray.shape

(4, 3)

In [16]:
mdarray.ndim

2

##### Key numerical operations

In [17]:
mdarray

array([[1, 4, 4],
       [4, 6, 2],
       [8, 8, 5],
       [5, 3, 8]])

In [18]:
mdarray2 = 2 * mdarray

In [19]:
mdarray2

array([[ 2,  8,  8],
       [ 8, 12,  4],
       [16, 16, 10],
       [10,  6, 16]])

In [20]:
mdarray

array([[1, 4, 4],
       [4, 6, 2],
       [8, 8, 5],
       [5, 3, 8]])

In [21]:
mdarray3 = mdarray + mdarray2

In [22]:
mdarray3

array([[ 3, 12, 12],
       [12, 18,  6],
       [24, 24, 15],
       [15,  9, 24]])

In [23]:
mdarray4 = mdarray3 + 10

In [24]:
mdarray4

array([[13, 22, 22],
       [22, 28, 16],
       [34, 34, 25],
       [25, 19, 34]])

In [26]:
np.array([10,20,10]).shape

(3,)

#### Few more interesting operations (statistical)

In [27]:
mdarray4

array([[13, 22, 22],
       [22, 28, 16],
       [34, 34, 25],
       [25, 19, 34]])

In [28]:
mdarray4.max()

34

In [29]:
mdarray4.min()

13

In [30]:
mdarray4.sum()

294

In [31]:
mdarray4.mean()

24.5

In [32]:
mdarray4.std()

6.689544080129826

In [33]:
mdarray4

array([[13, 22, 22],
       [22, 28, 16],
       [34, 34, 25],
       [25, 19, 34]])

In [34]:
mdarray4.shape

(4, 3)

In [35]:
mdarray4.reshape(3,4)

array([[13, 22, 22, 22],
       [28, 16, 34, 34],
       [25, 25, 19, 34]])

In [36]:
mdarray4.transpose()

array([[13, 22, 34, 25],
       [22, 28, 34, 19],
       [22, 16, 25, 34]])

#### Slicing 

In [53]:
mdarray4

array([[13, 22, 22],
       [22, 28, 16],
       [34, 34, 25],
       [25, 19, 34]])

In [55]:
mdarray4[3]

array([25, 19, 34])

In [38]:
mdarray4[3][1]

19

In [37]:
mdarray4[3,1]

19

In [49]:
mdarray5[1]

array([12,  8,  6])

In [58]:
mdarray4[1][2]

16

In [65]:
mdarray4[:1]

array([[13, 22, 22]])

In [66]:
mdarray4[:-1]

array([[13, 22, 22],
       [22, 28, 16],
       [34, 34, 25]])

In [59]:
mdarray5[:1]

array([[ 3,  2, 12]])

In [60]:
mdarray5[1:]

array([[12,  8,  6],
       [24, 14, 15],
       [15, -1, 24]])

In [61]:
mdarray5[:,:1]

array([[ 3],
       [12],
       [24],
       [15]])

In [62]:
mdarray5[:,:2]

array([[ 3,  2],
       [12,  8],
       [24, 14],
       [15, -1]])


#### Excercise: 

1. Create a numpy object of shape 4,4 with elements of float datatype
2. Find the sum of center 4 elements
2. Find the average of diagonal values

In [39]:
np.random.seed(200)

In [40]:
array1 = np.random.rand(4,4)

In [41]:
array1

array([[0.94763226, 0.22654742, 0.59442014, 0.42830868],
       [0.76414069, 0.00286059, 0.35742368, 0.90969489],
       [0.45608099, 0.98180271, 0.86735699, 0.98602751],
       [0.92326671, 0.30369331, 0.84610349, 0.12122197]])

In [42]:
array1.diagonal().mean()

0.48476795185730637

In [43]:
array1[1:3,1:3].sum()

2.2094439725868513

#### Few more faster tips to create specific type of NumPy arrays

In [29]:
zerosarray = 7* np.ones((3,5))

In [30]:
zerosarray

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [32]:
mdarray = np.arange(10,100,5)

In [33]:
mdarray

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

### Stacking Arrays

In [34]:
a = np.array([[0,1],[2,3]])

In [79]:
a

array([[0, 1],
       [2, 3]])

In [35]:
b = np.array([[4,5],[6,7]])

In [36]:
b

array([[4, 5],
       [6, 7]])

In [37]:
ab_hstack = np.hstack((a,b))
ab_vstack = np.vstack((a,b))

In [38]:
ab_hstack

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [39]:
ab_vstack

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [86]:
dotproductarray = np.dot(ab_hstack,ab_vstack)

In [87]:
dotproductarray

array([[48, 58],
       [72, 90]])